Use bicubic sampling for rough refractions in BaseMaterial3D
This improves rough refraction quality at a performance cost that
depends on the material's screen coverage.

TODO:

- Make it optional on a per-material basis or project setting.
  - Some materials don't really need it, since bicubic sampling
    would only improve quality marginally.
- Fix error on shader compilation:

ERROR: Condition "!actions.custom_samplers.has(function->arguments[j].tex_builtin)" is true. Continuing.
   at: _dump_node_code (servers/rendering/renderer_rd/shader_compiler_rd.cpp:1216)

- Inline some of the bicubic sampling functions to avoid conflicts
  with converted shaders?