[WIP] Remove unused PCSS soft shadow code [ci skip]
The code is no longer functional since the shaders were optimized,a
and needs to be redone from scratch.

TODO:

- The code compiles but the shader doesn't work (empty environment displays instead):

ERROR: Uniform buffer supplied (binding: 6) size (4128 does not match size of shader uniform: (4224).
   at: uniform_set_create (drivers/vulkan/rendering_device_vulkan.cpp:5350)