Add theme audio items and playback on common UI events
This allows themes to play sounds when hovering/pressing buttons,
typing text and using sliders.

A new "audio" theme item type is added to allow custom controls
to define their own audio streams, as well as benefit from the theme
override system.

Playback is handled by adding internal nodes at the top of the SceneTree,
and is not affected by pause or scene changes. Nodes are automatically freed
once playback is done. Polyphony is implicitly supported by creating a node
for each audio playback event.

`get_tree().create_audio_stream_player(stream: AudioStream, bus: StringName, volume_db: float)`
can now be used to play a sound non-positionally, without having to worry
about a parent node being freed and having the sound be cut off early.
This is useful to play one-off sounds such as announcer audio.

TODO:

- Reimplement `focus` audio playback to work with all Control-derived nodes.
  Perhaps also use different theme items for mouse/touch and keyboard/gamepad-induced focus
  (to prevent playing audio twice when clicking a button with mouse/touch).
- Fix BaseButton's `pressed_disabled` never being played as this isn't called
  on disabled buttons. SpinBox also has the same issue (started fixing,
  need to migrate to use `BIND_THEME_ITEM`).
- Return early in `SceneTree::create_audio_stream_player()` if using a bare
  AudioStream resource (useful to mute specific sounds with theme overrides
  without spamming errors).
- Fix theme audio overrides made in the inspector not persisting on scene
  reload for Control-derived nodes.
- Fix error on editor startup:

    ERROR: Parameter "data.tree" is null.
       at: get_tree (./scene/main/node.h:471)

  - Maybe ignore all theme audio calls in `Engine.is_editor_hint()`.
    See if this can be macro'd, also for the `get_tree()` check.

- Started fixing:
  - Make `--doctool` able to see audio theme items.
    - Done for BaseButton so far; other classes need to be migrated to use
      `BIND_THEME_ITEM` and a `theme_cache`. Theme item names must not conflict
      with existing theme items, so a `_sound` suffix may be needed.